services:
    server:
        container_name: estagios-server
        build: ./back-end
        ports:
            - 8000:8000
        networks:
            - net
        depends_on:
            - redis
            - mail
            - postgres
        environment:
            FRONTEND_URL: '*'
            NODE_ENV: production
            REDIS_URL: redis://redis:6379
            EMAIL_HOST: 'mail'
            EMAIL_PORT: 1025
            EMAIL_SENDER: 'estagiohub@email.com'
            EMAIL_USER: ''
            EMAIL_PASS: ''
            DB_HOST: postgres
            DB_PORT: 5432
            DB_NAME: estagios_db
            DB_USER: postgres
            DB_PASS: postgres
            DB_TYPE: postgres

    mail:
        container_name: smtp-mail-server
        image: axllent/mailpit
        ports:
            - 1025:1025
            - 8025:8025
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: true
            MP_SMTP_AUTH_ALLOW_INSECURE: true
            MP_VERBOSE: true
        networks:
            - net

    redis:
        container_name: redis-session-store
        image: redis
        command: redis-server --save
        ports:
            - 6379:6379
        networks:
            - net

    redis-commander:
        container_name: redis-commander
        image: rediscommander/redis-commander:latest
        environment:
            REDIS_HOST: redis
            REDIS_PORT: redis:6379
        ports:
            - 8081:8081
        networks:
            - net

    postgres:
        container_name: postgres-db
        image: postgres:latest
        environment:
            POSTGRES_DB: estagios_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
        networks:
            - net
        volumes:
            - postgres_data:/var/lib/postgresql/data

    adminer:
        container_name: postgres-admin
        image: adminer
        ports:
            - 8080:8080
        networks:
            - net

networks:
    net:
        driver: bridge

volumes:
    postgres_data:
