services:
    - type: web
      runtime: node
      name: estagiohub-server
      numInstances: 1
      plan: free
      branch: main
      autoDeploy: false
      buildCommand: npm pkg delete scripts.prepare && npm i && npm run build
      startCommand: npm run start
      envVars:
          - key: NODE_ENV
            value: production
      rootDir: back-end
