services:
    - type: web
      runtime: docker
      name: estagiohub-server
      numInstances: 1
      plan: free
      branch: main
      autoDeploy: false
      buildCommand: docker build -p 8000:8000 .
      rootDir: back-end
