# @name start-new-internship
# @prompt token
POST {{baseUrl}}/internship/start-new-internship
Content-Type: application/json
Access-Control-Allow-Credentials: true
Authorization: Bearer {{token}}

# TODO: test with items in schedule
{
    "classification": "mandatory",
    "division": "Desenvolvimento",
    "monthlyStipend": 5000,
    "organizationCnpj": "19131243000197",
    "organizationSupervisor": {
        "email": "supervisor@example.com",
        "name": "Supervisor da empresa",
        "position": "supervisor"
    },
    "period": {
        "startDate": "2024-01-01",
        "expectedEndDate": "2024-12-31"
    },
    "schedule": [],
    "studentId": 1,
    "supervisorId": 1,
    "transportationAid": 3,
    "weeklyHours": {
        "mondayToFriday": { 
            "startTime": 8, 
            "endTime": 12 
        },
        "mondayToFridaySecondary": null,
        "saturday": null
    },
    "workSituation": "onsite"
}

###
# @name searchInternships
# @prompt token
# @prompt searchTerm
# @prompt limit 10
# @prompt offset 0
GET {{baseUrl}}/internship?searchTerm={{searchTerm}}&limit={{limit}}&offset={{offset}}
Content-Type: application/json
Access-Control-Allow-Credentials: true
Authorization: Bearer {{token}}

###
# @name findInternshipByID
# @prompt token
# @prompt id
GET {{baseUrl}}/internship/{{id}}
Content-Type: application/json
Access-Control-Allow-Credentials: true
Authorization: Bearer {{token}}

###
# @name cancelInternshipRequest
# @prompt token
# @prompt id
POST {{baseUrl}}//internship/{{id}}/cancel-new-internship
Content-Type: application/json
Access-Control-Allow-Credentials: true
Authorization: Bearer {{token}}

###
# @name approveInternshipRequest
# @prompt token
# @prompt id
POST {{baseUrl}}//internship/{{id}}/approve-new-internship
Content-Type: application/json
Access-Control-Allow-Credentials: true
Authorization: Bearer {{token}}

###
# @name rejectInternshipRequest
# @prompt token
# @prompt id
POST {{baseUrl}}//internship/{{id}}/reject-new-internship
Content-Type: application/json
Access-Control-Allow-Credentials: true
Authorization: Bearer {{token}}
