# @name login
# @prompt email
# @prompt password
POST {{baseUrl}}/student/login
Content-Type: application/json
Access-Control-Allow-Credentials: true

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###
# @name register
# @prompt fullName
# @prompt email
# @prompt password
POST {{baseUrl}}/student/register
Content-Type: application/json
Access-Control-Allow-Credentials: true

{
    "fullName": "{{fullName}}",
    "email": "{{email}}",
    "password": "{{password}}",
    "repeatPassword": "{{password}}"
}

###
# @name searchStudents
# @prompt token
# @prompt searchTerm
# @prompt limit 10
# @prompt offset 0
GET {{baseUrl}}/student?searchTerm={{searchTerm}}&limit={{limit}}&offset={{offset}}
Content-Type: application/json
Access-Control-Allow-Credentials: true
Authorization: Bearer {{token}}
