# @name login
# @prompt email
# @prompt password
POST {{baseUrl}}/student/login
Content-Type: application/json
Access-Control-Allow-Credentials: true

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###
# @name register
# @prompt fullName
# @prompt email
# @prompt password
POST {{baseUrl}}/student/register
Content-Type: application/json
Access-Control-Allow-Credentials: true

{
    "fullName": "{{fullName}}",
    "email": "{{email}}",
    "password": "{{password}}",
    "repeatPassword": "{{password}}"
}

###
# @name updateStudent
# @prompt token
# @prompt fullName
# @prompt academicClass
# @prompt academicId
# @prompt phone
# @prompt whatsapp
# @prompt rg
# @prompt street
# @prompt city
# @prompt district
# @prompt postalCode
# @prompt state
# @prompt number
# @prompt additionalInfo
PUT {{baseUrl}}/student
Content-Type: application/json
Access-Control-Allow-Credentials: true
Authorization: Bearer {{token}}

{
    "fullName": "{{fullName}}",
    "academicClass": "{{academicClass}}",
    "academicId": "{{academicId}}",
    "phone": "{{phone}}",
    "whatsapp": "{{whatsapp}}",
    "rg": "{{rg}}",
    "address": {
        "street": "{{street}}",          
        "city": "{{city}}",             
        "district": "{{district}}",     
        "postalCode": "{{postalCode}}", 
        "state": "{{state}}",           
        "number": "{{number}}",         
        "additionalInfo": "{{additionalInfo}}" 
    }
}

###
# @name updateStudentByUserId
# @prompt token
# @prompt userId
# @prompt fullName
# @prompt academicClass
# @prompt academicId
# @prompt phone
# @prompt whatsapp
# @prompt rg
# @prompt street
# @prompt city
# @prompt district
# @prompt postalCode
# @prompt state
# @prompt number
# @prompt additionalInfo
PUT {{baseUrl}}/student/user/{{userId}}
Content-Type: application/json
Access-Control-Allow-Credentials: true
Authorization: Bearer {{token}}

{
    "fullName": "{{fullName}}",
    "academicClass": "{{academicClass}}",
    "academicId": "{{academicId}}",
    "phone": "{{phone}}",
    "whatsapp": "{{whatsapp}}",
    "rg": "{{rg}}",
    "address": {
        "street": "{{street}}",         
        "city": "{{city}}",              
        "district": "{{district}}",      
        "postalCode": "{{postalCode}}",  
        "state": "{{state}}",           
        "number": "{{number}}",          
        "additionalInfo": "{{additionalInfo}}"
    }
}

###
# @name searchStudents
# @prompt token
# @prompt limit 10
# @prompt offset 0
# @prompt searchTerm
GET {{baseUrl}}/student?searchTerm={{searchTerm}}&limit={{limit}}&offset={{offset}}
Content-Type: application/json
Access-Control-Allow-Credentials: true
Authorization: Bearer {{token}}
